package Lab7;
import java.beans.Expression;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ����ʵ����.java
//  @ Date : 2016/11/28
//  @ Author : 

public class Command {
	private String command;
	private Expression exp;
	private Answer ans;


	public void judge(String command) {
	
	}
	
	public void simplify() {
		Simplify sim = new Simplify(command, exp);
	}
	
	public void derivate(Expression exp, String command) {
	
	}
	
	public void setCommand(String newCom, Expression newExp) {
		this.command = newCom;
		this.exp = newExp;
	}
	
	
}
