package Lab7;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ����ʵ����.java
//  @ Date : 2016/11/28
//  @ Author : 

public class Command {
	private String command;
	private Expression exp;
	private Answer ans;


	public boolean judge() {
		JudgeCommand jc = new JudgeCommand(command);
		return jc.judgeCommand();
	}
	
	public void simplify() {
		if (judge()) {
			Simplify sim = new Simplify(command, exp.getExpression());			
		}
	}
	
	public void derivate(Expression exp, String command) {
	
	}
	
	public void setCommand(String newCom, Expression newExp) {
		this.command = newCom;
		this.exp = newExp;
	}
	
	
}
