package Lab7;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ���ʽʵ����.java
//  @ Date : 2016/11/28
//  @ Author : 

public class Expression {
	private String exp;
	public Expression() {
		exp = "";
	}
	public Expression(String exp) {
		this.exp = exp;
	}
	
	public void judge(String expression) {
	
	}
	
	public void mergeExp(String expression) {
	
	}
	
	public void getExpression() {
	
	}
	
	public void setExpresssion(String newExp) {
	
	}
}
