package Lab7;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ��������߽���.java
//  @ Date : 2016/11/28
//  @ Author : 
//
//




public class InputCommand {
	public void inCommand() {
	
	}
}
