package Lab7;
import java.util.Scanner;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ������ʽ�߽���.java
//  @ Date : 2016/11/28
//  @ Author : 
//
//




public class InputExpression{
	public void inExpression() {

	}
}
