package Lab7;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : �жϱ��ʽ��ʽ������.java
//  @ Date : 2016/11/28
//  @ Author : 

public class JudgeExpression {
		
	/**
	 * Judge whether char a is a operative symbol. 
	 * @param a char
	 * @return true or false
	 */
	public static boolean isSymbol(final char a) {
		return (a == '+' || a == '*' || a == '-' || a == '^');
	}
	/**
	 * Judge whether char a is a number.
	 * 
	 * @param scanCharacter char
	 * @return true or false
	 */
	public static boolean isNumber(final char  scanCharacter) {
		return (scanCharacter >= '0' && scanCharacter <= '9');
	}

	/**
	 * Judge whether char a is a letter.
	 * 
	 * @param a char
	 * @return true or false
	 */
	public static boolean isLetter(final char a) {
		return ((a >= 'A' && a <= 'Z') || (a >= 'a' && a <= 'z'));
	}
	
	/**
	 * Get a substring of number at the start position i in the string input.
	 * 
	 * @param input
	 *            string
	 * @param index
	 *            int
	 * @return substring
	 */
	public static String getNumStr(final String input, final int index) {
		int j = index + 1;
		while (j < input.length() && isNumber(input.charAt(j))) {
			j++;
		}
		return input.substring(index, j);
	}	
	
	/**
	 * Get a substring of variable at the start position i in the string input.
	 * 
	 * @param input
	 *            string
	 * @param i
	 *            int
	 * @return substring
	 */
	public static String getVarStr(final String input, final int i) {
		int j = i + 1;
		while (j < input.length() && isLetter(input.charAt(j))) {
			j++;
		}
		return input.substring(i, j);
	}	
	
	public boolean judgeExpression(final String fun) {
		int cntNum = 0, cntSymbol = 0;
		char currentChar = '*';
		boolean errorDetected = false;
		if (fun.length() < 1 || isSymbol(fun.charAt(0)) || isSymbol(fun.charAt(fun.length() - 1))) {
		//symbol not allowed at the head or tail of expression
			errorDetected = true;
		}else{
			for (int i = 0; i < fun.length(); i++) {
				currentChar = fun.charAt(i);
				if (isNumber(currentChar)) {
					final String l = getNumStr(fun, i);
					if ((i + l.length() < fun.length()) 
							&& 	fun.charAt(i + l.length()) == '^') {
						// Avoid "2^y",etc
						errorDetected = true; 
						}
					i = i + l.length() - 1; // skip the detected number
					cntNum = cntNum + l.length();
					cntSymbol = 0;
				} else if (isLetter(currentChar)) {
					final String l = getVarStr(fun, i); 
					final int len = l.length();
					if (i + len < fun.length() && fun.charAt(i + len) == '^') {
						// Avoid situation like "y^2^2",etc
						if (isNumber(fun.charAt(i + len + 1))) {
							final String ll = getNumStr(fun, i + len + 1);
							if ((i + len + 1 + ll.length() < fun.length())
									&& (fun.charAt(i + len + 1 + ll.length()) == '^')) {
								errorDetected = true;
							}
	
						} else {
							// if power is not a number
							errorDetected = true;
						}
					}
					i = i + len - 1;
					cntNum = 0;
					cntSymbol = 0;
				} else if (cntSymbol == 0 && isSymbol(currentChar)) { 
					// Avoid continues symbols
					cntSymbol++;
					cntNum = 0;
				} else {
					errorDetected = true;
				}
			}
		}
		
		return !errorDetected;	
	}
}
