package Lab7;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : �ж����������.java
//  @ Date : 2016/11/28
//  @ Author : 

public class JudgeInput {
	public int judgeInput(final String input) {
		final int 	minLength = 6;
		int 		inputType;
		if (input.charAt(0) == '!') {
			if (input.length() < minLength) {
				inputType = 3; // The command is too short, so error
			}
			if (input.substring(1, 4).equals("d/d")) {
				inputType = 1; // It is a derivation command
			} else if (input.substring(1, 9).equals("simplify")) {
				inputType = 0; // It is simplification command
			} else {
				inputType = 3; // Error
			}
		} else {
			inputType = 2; // Expression
		}
		return inputType;		
	}
}
