package Lab7;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : �жϱ��ʽ��ʽ������.java
//  @ Date : 2016/11/28
//  @ Author : 

public class JudgeExpression {		

	
	public boolean judgeExpression(final String fun) {
		OperateString ops = new OperateString();
		int cntNum = 0, cntSymbol = 0;
		char currentChar = '*';
		boolean errorDetected = false;
		if (fun.length() < 1 || ops.isSymbol(fun.charAt(0)) || ops.isSymbol(fun.charAt(fun.length() - 1))) {
		//symbol not allowed at the head or tail of expression
			errorDetected = true;
		}else{
			for (int i = 0; i < fun.length(); i++) {
				currentChar = fun.charAt(i);
				if (ops.isNumber(currentChar)) {
					final String l = ops.getNumStr(fun, i);
					if ((i + l.length() < fun.length()) 
							&& 	fun.charAt(i + l.length()) == '^') {
						// Avoid "2^y",etc
						errorDetected = true; 
						}
					i = i + l.length() - 1; // skip the detected number
					cntNum = cntNum + l.length();
					cntSymbol = 0;
				} else if (ops.isLetter(currentChar)) {
					final String l = ops.getVarStr(fun, i); 
					final int len = l.length();
					if (i + len < fun.length() && fun.charAt(i + len) == '^') {
						// Avoid situation like "y^2^2",etc
						if (ops.isNumber(fun.charAt(i + len + 1))) {
							final String ll = ops.getNumStr(fun, i + len + 1);
							if ((i + len + 1 + ll.length() < fun.length())
									&& (fun.charAt(i + len + 1 + ll.length()) == '^')) {
								errorDetected = true;
							}
	
						} else {
							// if power is not a number
							errorDetected = true;
						}
					}
					i = i + len - 1;
					cntNum = 0;
					cntSymbol = 0;
				} else if (cntSymbol == 0 && ops.isSymbol(currentChar)) { 
					// Avoid continues symbols
					cntSymbol++;
					cntNum = 0;
				} else {
					errorDetected = true;
				}
			}
		}
		
		return !errorDetected;	
	}
}
