package Lab7;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : �жϱ��ʽ��ʽ������.java
//  @ Date : 2016/11/28
//  @ Author : 

public class JudgeExpression {		

	public static boolean judgeExpression(final String fun) {
		Expression exp = new Expression(fun);
		return exp.judge();
	}
	
		
}
