package Lab7;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ִ�н����������.java
//  @ Date : 2016/11/28
//  @ Author : 
//
//




public class Output {
	public void print(String str) {
		System.out.println(str);
	}
}
