package Control;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ִ�������������.java
//  @ Date : 2016/11/28
//  @ Author : 

import Entity.Command;

public class Derivate {
	public void derivate(Command com) {
		com.derivate();
	}
}
