package Control;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : �ж������ʽ������.java
//  @ Date : 2016/11/28
//  @ Author : 
//
//

import Entity.Command;
import Entity.OperateString;

public class JudgeCommand {
	
	public boolean judgeLegal(String input) {
		Command com = new Command();
		boolean flag = false;
		
		JudgeInput ji = new JudgeInput();
		int type = ji.judgeInput(input);
		
		if (type == 1) {
			com.setCommand(input);
			flag = com.judgeDerivate();
		} else if (type == 2) {
			com.setCommand(input);
			flag = com.judgeSimplify();
		}
		return flag;
	}
}
