package Control;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : �������߽���.java
//  @ Date : 2016/11/28
//  @ Author : 
//
//

import Boundary.Output;
import Entity.Answer;

public class OutputAnswer{
	private Answer ans;
	public OutputAnswer(Answer ans) {
		Output output = new Output();
		output.print(ans.getAnswer());
	}
}
