//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ִ�л������������.java
//  @ Date : 2016/11/28
//  @ Author : 

package Control;

import Entity.Command;

public class Simplify {
	
	public void simplify(Command com) {
		com.simplify();
	}
}
