package Boundary;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ��������߽���.java
//  @ Date : 2016/11/28
//  @ Author : 
//
//

import java.util.Scanner;

public class Input {
	private String input;
	final Scanner inSys = new Scanner(System.in);
	
	/**
	 * @return the input
	 */
	public String getInput() {
		return input;
	}


	/**
	 * @param input the input to set
	 */
	public void setInput(String input) {
		this.input = input;
	}


	public void IN() {
		this.input = inSys.nextLine();
	}
}
